#!/bin/bash
# The logic to stop your application should be put in this script.

INSTALL_DIR=${OPENSHIFT_HOMEDIR}/app-root/runtime

echo "Stopping elasticsearch."
kill -9 `cat ${INSTALL_DIR}/elasticsearch/run/elasticsearch.pid`

echo "Stopping nginx."
kill -9 `cat ${INSTALL_DIR}/nginx/run/nginx.pid`
exit 0