#!/bin/bash
# The logic to stop your application should be put in this script.

INSTALL_DIR=${OPENSHIFT_HOMEDIR}/app-root/runtime

echo "Stopping elasticsearch."
pgrep -f elastic | xargs kill -9 $1

echo "Stopping nginx."
pgrep -f nginx | xargs kill -9 $1
exit 0